Cascading Style Sheets (CSS) is a stylesheet language used to describe the presentation of a
document written in HTML or XML (including XML dialects such as SVG, MathML or XHTML). CSS
describes how elements should be rendered on screen, on paper, in speech, or on other media.

https://developer.mozilla.org/en-US/docs/Web/CSS

== How it Works

Web browsers apply CSS rules to a document to affect how they are displayed. A CSS rule is formed from:

    - A set of properties, which have values set to update how the HTML content is displayed, for example, I want my element's width to be 50% of its parent element, and its background to be red.
    - A selector, which selects the element(s) you want to apply the updated property values to. For example, I want to apply my CSS rule to all the paragraphs in my HTML document.

A set of CSS rules contained within a stylesheet determines how a webpage should look.

== Examples in this project

Many examples in this projects are from online tutorials and reference site. I have simply collected them here
for learning purpose. In many cases modified for learning purpose as well.

Here are few good references to learn about HTML/CSS/JavaScript

- https://www.w3schools.com/html/default.asp
- https://developer.mozilla.org/en-US/docs/Web

