JavaScript (JS) is a lightweight interpreted or JIT-compiled programming language
with first-class functions. While it is most well-known as the scripting language
for Web pages, many non-browser environments also use it, such as Node.js, Apache
CouchDB and Adobe Acrobat. JavaScript is a prototype-based, multi-paradigm, dynamic
language, supporting object-oriented, imperative, and declarative
(e.g. functional programming) styles.

https://developer.mozilla.org/en-US/docs/Web/JavaScript

== What is JavaScript, really?

JavaScript ("JS" for short) is a full-fledged dynamic programming language that, when applied to an HTML document,
can provide dynamic interactivity on websites. It was invented by Brendan Eich, co-founder of the Mozilla project,
the Mozilla Foundation, and the Mozilla Corporation.

See `learn-js`. It contains many examples mentioned from
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference


== Run and Testing JavaScript

A tradition way to run JS is to use a browser and use the "script" tag in html file.

Now a day, you can easy run JS with NodeJS (node) command line. See `nodejs-starter`.

== What is the DOM?

What is the DOM?Section

The Document Object Model (DOM) is a programming interface for HTML and XML documents. It represents the page so that programs can change the document structure, style, and content. The DOM represents the document as nodes and objects. That way, programming languages can connect to the page.

A Web page is a document. This document can be either displayed in the browser window or as the HTML source. But it is the same document in both cases. The Document Object Model (DOM) represents that same document so it can be manipulated. The DOM is an object-oriented representation of the web page, which can be modified with a scripting language such as JavaScript.

The W3C DOM and WHATWG DOM standards are implemented in most modern browsers. Many browsers extend the standard, so care must be exercised when using them on the web where documents may be accessed by various browsers with different DOMs.

https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction

== The DOM API Reference

https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model

== JS Notes

=== What is "Objects' constructor function"?

Object Types (Blueprints) (Classes)

Sometimes we need a "blueprint" for creating many objects of the same "type".

The way to create an "object type", is to use an object constructor function.

In the example below, function Person() is an object constructor function.

Objects of the same type are created by calling the constructor function with the new keyword:

----
function Person(first, last, age, eye) {
  this.firstName = first;
  this.lastName = last;
  this.age = age;
  this.eyeColor = eye;
}
var myFather = new Person("John", "Doe", 50, "blue");
var myMother = new Person("Sally", "Rally", 48, "green");
----

TIPS: It is considered good practice to name constructor functions with an upper-case first letter.

NOTE: We also learned that you can not add a new property to an existing object constructor. To add a new property to a constructor, you must add it to the constructor function. If must, then you need to use "prototype".

=== What is "this"?

In a constructor function this does not have a value. It is a substitute for the new object. The value of this will become the new object when a new object is created.

https://www.w3schools.com/js/js_object_constructors.asp

NOTE: It's easy to make mistake to invoke constructor function without "new".
In this case, the `this` will be the "global" object of the platform (eg:
`window` in browser, or `global` in nodejs etc)


=== Built-In Constructor Functions

----
var x1 = new Object();    // A new Object object
var x2 = new String();    // A new String object
var x3 = new Number();    // A new Number object
var x4 = new Boolean();   // A new Boolean object
var x5 = new Array();     // A new Array object
var x6 = new RegExp();    // A new RegExp object
var x7 = new Function();  // A new Function object
var x8 = new Date();      // A new Date object


ALSO:

Use object literals {} instead of new Object().

Use string literals "" instead of new String().

Use number literals 12345 instead of new Number().

Use boolean literals true / false instead of new Boolean().

Use array literals [] instead of new Array().

Use pattern literals /()/ instead of new RegExp().

Use function expressions () {} instead of new Function().
----
