RequireJS is a JavaScript file and module loader. It is optimized for in-browser use, but it can be used in other JavaScript environments, like Rhino and Node. Using a modular script loader like RequireJS will improve the speed and quality of your code.

RequireJS takes a different approach to script loading than traditional <script> tags. While it can also run fast and optimize well, the primary goal is to encourage modular code. As part of that, it encourages using module IDs instead of URLs for script tags.

https://requirejs.org/

== Writing Modules

You only need "require.js" to load other ".js" files as "module".

A simple way to define module is to use the "define()". If you
have legacy JS that needs to be treated as module, then you need
to custom define with "require.config"

== Examples

- https://github.com/volojs/create-template[Simple one page app]
- https://github.com/requirejs/example-multipage[Multipage app]

== Further Reading

- http://www.adequatelygood.com/JavaScript-Module-Pattern-In-Depth.html
