JavaScript (JS) is a lightweight interpreted or JIT-compiled programming language
with first-class functions. While it is most well-known as the scripting language
for Web pages, many non-browser environments also use it, such as Node.js, Apache
CouchDB and Adobe Acrobat. JavaScript is a prototype-based, multi-paradigm, dynamic
language, supporting object-oriented, imperative, and declarative
(e.g. functional programming) styles.

https://developer.mozilla.org/en-US/docs/Web/JavaScript

== Run and Testing JavaScript

A tradition way to run JS is to use a browser and use the "script" tag in html file.

Now a day, you can easy run JS with NodeJS (node) command line. See `nodejs-starter`.

== What is the DOM?

What is the DOM?Section

The Document Object Model (DOM) is a programming interface for HTML and XML documents. It represents the page so that programs can change the document structure, style, and content. The DOM represents the document as nodes and objects. That way, programming languages can connect to the page.

A Web page is a document. This document can be either displayed in the browser window or as the HTML source. But it is the same document in both cases. The Document Object Model (DOM) represents that same document so it can be manipulated. The DOM is an object-oriented representation of the web page, which can be modified with a scripting language such as JavaScript.

The W3C DOM and WHATWG DOM standards are implemented in most modern browsers. Many browsers extend the standard, so care must be exercised when using them on the web where documents may be accessed by various browsers with different DOMs.

https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction

== The DOM API Reference

https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model